import Head from "next/head";
import LandingPage from "../components/LandingPage/LandingPage";

export default function Home() {
  return (
    <div className="h-screen bg-gray-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPage />
    </div>
  );
}
