const URL = "https://p.scdn.co/mp3-preview/40821a698364f0bf84b15bcc71a40ef813fff0e1?cid=f6a40776580943a7bc5173125a1e8832";

export const songs = [
  {
    id: 1,
    title: "DJ Khaled Featuring",
    artist: "Dj Khaled",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3173",
  },
  {
    id: 2,
    title: "DJ Khaled Featuring",
    artist: "Cigarette after Sex",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3172",
  },
  {
    id: 3,
    title: "DJ Khaled Featuring",
    artist: "Edtyta Gomiak",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3175",
  },
  {
    id: 4,
    title: "DJ Khaled Featuring",
    artist: "Tintin Mihigo",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
  {
    id: 5,
    title: "DJ Khaled Featuring",
    artist: "Samurai Thung",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
  {
    id: 6,
    title: "DJ Khaled Featuring",
    artist: "Albatros Country",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
  {
    id: 4,
    title: "DJ Khaled Featuring",
    artist: "Tintin Mihigo",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
  {
    id: 5,
    title: "DJ Khaled Featuring",
    artist: "Samurai Thung",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
  {
    id: 6,
    title: "DJ Khaled Featuring",
    artist: "Albatros Country",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
  {
    id: 4,
    title: "DJ Khaled Featuring",
    artist: "Tintin Mihigo",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
  {
    id: 5,
    title: "DJ Khaled Featuring",
    artist: "Samurai Thung",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
  {
    id: 6,
    title: "DJ Khaled Featuring",
    artist: "Albatros Country",
    audioSrc: URL,
    img: "https://api.lorem.space/image/album?hash=3154",
  },
];
