name: build Yokaa-frontend app
on:
  push:
    branches: ["ft/**", "fix/**", "doc/**", "chore/**", "refact/**", "style/**"]
  pull_request:
    types: [opened]
jobs:
  lint_and_build:
    name: Lint & build app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: using latest version of Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm i
      - name: Caching node_modules
        uses: actions/cache@v3
        with:
          key: modules-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - name: Run lint
        run: npm run lint
      - name: Build app
        run: npm run build
