name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: npm ci
      - name: Setup the author
        run: git config --global user.name "${{ github.actor }}" && git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Run release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: End message
        run: echo "Release done!!!!! 🚀"
